import { Product, Category, HeroSlide } from "@/types";

export interface SubCategory {
  id: string;
  name: string;
  slug: string;
  parentSlug: string;
}

export const MAIN_BRACELET_CATEGORIES: Category[] = [
  {
    id: "cat-gemstones",
    name: "Gemstone Bracelets",
    slug: "gemstones",
    description: "100% Natural, Unheated Vedic Gemstone energy bracelets (Pyrite, Amethyst, Citrine, Tiger's Eye & more).",
    image_url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&q=80",
    parent_id: null,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-zodiac",
    name: "Zodiac Bracelets",
    slug: "zodiac",
    description: "Tailored Birthstone & Rashi alignment bracelets for all 12 astrological signs.",
    image_url: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&q=80",
    parent_id: null,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-navgraha",
    name: "Navgraha & Planetary",
    slug: "navgraha",
    description: "Sacred 9-Planet Navgraha & individual planetary ruler energy bracelets (Sun, Moon, Jupiter, Saturn).",
    image_url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
    parent_id: null,
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-protection",
    name: "Protection Bracelets",
    slug: "protection",
    description: "Evil Eye, Black Obsidian, Nazar Protection, Hamsa & Black Tourmaline auric shield bracelets.",
    image_url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80",
    parent_id: null,
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-prosperity",
    name: "Abundance & Wealth",
    slug: "prosperity",
    description: "Citrine, Pyrite, Green Aventurine & Tiger's Eye bracelets consecrated for wealth & financial growth.",
    image_url: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80",
    parent_id: null,
    sort_order: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-chakras",
    name: "Chakra Healing",
    slug: "chakras",
    description: "7-Chakra & Kundalini balancing crystal stone bracelets for emotional alignment & vital health.",
    image_url: "https://images.unsplash.com/photo-1567225557594-88d73e55f2cb?w=800&q=80",
    parent_id: null,
    sort_order: 6,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-rudraksha",
    name: "Rudraksha & Vedic",
    slug: "rudraksha",
    description: "Original Nepal Mukhi Rudraksha, Tulsi, Sphatik, Sandalwood & Navratna sacred wrist Malas.",
    image_url: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=80",
    parent_id: null,
    sort_order: 7,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-love",
    name: "Love & Relationships",
    slug: "love",
    description: "Rose Quartz, Heart Chakra & Relationship Harmony bracelets for unconditional love & emotional healing.",
    image_url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80",
    parent_id: null,
    sort_order: 8,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-intention",
    name: "Intention & Focus",
    slug: "intention",
    description: "Manifestation, Confidence, Peace, Motivation & Study Focus mental clarity bracelets.",
    image_url: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80",
    parent_id: null,
    sort_order: 9,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-premium",
    name: "Premium & Custom",
    slug: "premium",
    description: "Gold-Plated, 925 Sterling Silver, Custom Name & Birthstone luxury designer bracelets.",
    image_url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
    parent_id: null,
    sort_order: 10,
    created_at: new Date().toISOString(),
  },
];

export const YOGINEE_CATEGORIES = MAIN_BRACELET_CATEGORIES;

export const BRACELET_SUB_CATEGORIES: Record<string, string[]> = {
  gemstones: [
    "Pyrite Bracelet", "Amethyst Bracelet", "Rose Quartz Bracelet", "Citrine Bracelet",
    "Tiger's Eye Bracelet", "Black Tourmaline Bracelet", "Labradorite Bracelet", "Moonstone Bracelet",
    "Green Aventurine Bracelet", "Carnelian Bracelet", "Lapis Lazuli Bracelet", "Amazonite Bracelet",
    "Aquamarine Bracelet", "Garnet Bracelet", "Smoky Quartz Bracelet", "Clear Quartz Bracelet",
    "Obsidian Bracelet", "Malachite Bracelet", "Bloodstone Bracelet"
  ],
  zodiac: [
    "Aries Bracelet", "Taurus Bracelet", "Gemini Bracelet", "Cancer Bracelet",
    "Leo Bracelet", "Virgo Bracelet", "Libra Bracelet", "Scorpio Bracelet",
    "Sagittarius Bracelet", "Capricorn Bracelet", "Aquarius Bracelet", "Pisces Bracelet"
  ],
  navgraha: [
    "Navgraha 9-Planet Bracelet", "Sun / Surya Bracelet", "Moon / Chandra Bracelet",
    "Mars / Mangal Bracelet", "Mercury / Budh Bracelet", "Jupiter / Guru Bracelet",
    "Venus / Shukra Bracelet", "Saturn / Shani Bracelet", "Rahu Protection Bracelet", "Ketu Energy Bracelet"
  ],
  protection: [
    "Evil Eye Protection Bracelet", "Nazar Protection Bracelet", "Hamsa Hand Bracelet",
    "Black Obsidian Shield Bracelet", "Black Tourmaline Protection Bracelet",
    "Hematite Grounding Bracelet", "Tiger's Eye Shield", "Rudraksha Protection Wristlet"
  ],
  prosperity: [
    "Pyrite Prosperity Bracelet", "Citrine Abundance Bracelet", "Green Aventurine Luck Bracelet",
    "Tiger's Eye Wealth Bracelet", "Money Attraction Bracelet", "Success & Fortune Bracelet",
    "Business Growth Bracelet"
  ],
  chakras: [
    "7 Chakra Energy Bracelet", "Root Chakra Bracelet", "Sacral Chakra Bracelet",
    "Solar Plexus Bracelet", "Heart Chakra Healing Bracelet", "Throat Chakra Bracelet",
    "Third Eye Chakra Bracelet", "Crown Chakra Wisdom Bracelet"
  ],
  rudraksha: [
    "5 Mukhi Nepal Rudraksha Bracelet", "7 Mukhi Mahalaxmi Rudraksha Bracelet",
    "9 Mukhi Durga Rudraksha Bracelet", "Gauri Shankar Rudraksha Bracelet",
    "Sacred Tulsi Beads Bracelet", "Sphatik Crystal Bracelet", "Sandalwood Meditation Bracelet",
    "Navratna Sacred 9-Gem Bracelet", "Om Mahadev Trishul Bracelet"
  ],
  love: [
    "Rose Quartz Love Bracelet", "Self-Love & Harmony Bracelet", "Couple Connection Bracelet",
    "Relationship Balance Bracelet", "Emotional Healing Bracelet"
  ],
  intention: [
    "Manifestation Power Bracelet", "Confidence & Courage Bracelet", "Focus & Study Bracelet",
    "Peace & Calm Bracelet", "Positivity & New Beginnings"
  ],
  premium: [
    "Gold-Plated Gemstone Bracelet", "925 Sterling Silver Crystal Bracelet",
    "Luxury Navratna Gold Bracelet", "Custom Name & Zodiac Bracelet",
    "Personalized Birthstone Bracelet"
  ]
};

export const YOGINEE_HERO_SLIDES: HeroSlide[] = [
  {
    id: "slide-1",
    image_url: "/images/banner1.png",
    heading: "Guiding You Towards Clarity, Balance & Cosmic Harmony",
    subheading: "Empowering your journey with authentic gemstone & Vedic energy bracelets.",
    cta_text: "Explore Energized Bracelets",
    cta_link: "/products",
    sort_order: 1,
    is_active: true,
  },
  {
    id: "slide-2",
    image_url: "/images/cosmos-banner.jpg",
    heading: "Decode the Cosmos. Discover Your True Path.",
    subheading: "Sacred Navgraha, Pyrite Prosperity & 7-Chakra Healing Bracelets.",
    cta_text: "Shop Zodiac Collection",
    cta_link: "/products?category=zodiac",
    sort_order: 2,
    is_active: true,
  },
  {
    id: "slide-3",
    image_url: "/images/yantra-cosmos-banner.jpg",
    heading: "Pyrite Prosperity & Evil Eye Protection Bracelets",
    subheading: "Consecrated with Vedic mantras for wealth, luck, and ultimate protection.",
    cta_text: "Shop Wealth Bracelets",
    cta_link: "/products?category=prosperity",
    sort_order: 3,
    is_active: true,
  },
];

export const YOGINEE_PRODUCTS: Product[] = [
  {
    id: "brac-pyrite-1",
    title: "Golden Pyrite Wealth & Prosperity Bracelet (8mm Certified Beads)",
    slug: "golden-pyrite-wealth-prosperity-bracelet",
    description: "Original Natural Golden Pyrite (Fool's Gold) bracelet. Known as the ultimate Money Magnet stone. Consecrated with Goddess Lakshmi mantras for rapid wealth creation, business growth, and shielding from negative energy.",
    category_id: "cat-prosperity",
    category: MAIN_BRACELET_CATEGORIES[4],
    price: 1899,
    sale_price: 1299,
    sale_start: null,
    sale_end: null,
    sku: "BRAC-PYR-8MM",
    stock_quantity: 45,
    track_inventory: true,
    allow_backorders: true,
    status: "active",
    meta_title: "Golden Pyrite Money Attraction Bracelet - Yoginee",
    meta_description: "Natural certified Pyrite bracelet for wealth and prosperity.",
    og_image_url: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80",
    tags: ["Best Seller", "Pyrite", "Abundance", "Wealth", "Protection"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    avg_rating: 4.9,
    review_count: 184,
    images: [
      { id: "img-p1", product_id: "brac-pyrite-1", image_url: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80", sort_order: 1, alt_text: "Pyrite Bracelet" },
    ],
  },
  {
    id: "brac-citrine-1",
    title: "Natural Citrine Abundance & Money Magnet Bracelet",
    slug: "natural-citrine-abundance-money-magnet-bracelet",
    description: "Genuine Sun-heated Citrine crystal bracelet. Governed by Jupiter (Guru). Awakens merchant luck, financial abundance, optimism, and solar plexus confidence.",
    category_id: "cat-prosperity",
    category: MAIN_BRACELET_CATEGORIES[4],
    price: 1999,
    sale_price: 1499,
    sale_start: null,
    sale_end: null,
    sku: "BRAC-CIT-8MM",
    stock_quantity: 30,
    track_inventory: true,
    allow_backorders: true,
    status: "active",
    meta_title: "Natural Citrine Abundance Bracelet - Yoginee",
    meta_description: "Certified Citrine crystal bracelet for wealth luck.",
    og_image_url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&q=80",
    tags: ["Best Seller", "Citrine", "Jupiter", "Abundance", "Success"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    avg_rating: 4.9,
    review_count: 112,
    images: [
      { id: "img-c1", product_id: "brac-citrine-1", image_url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&q=80", sort_order: 1, alt_text: "Citrine Bracelet" },
    ],
  },
  {
    id: "brac-navgraha-1",
    title: "Sacred Navgraha 9-Planet Alignment Gemstone Bracelet",
    slug: "sacred-navgraha-9-planet-alignment-bracelet",
    description: "Authentic 9-Planet Navgraha energy bracelet combining Ruby, Pearl, Red Coral, Emerald, Yellow Sapphire, Diamond Quartz, Blue Sapphire, Hessonite & Cat's Eye. Balances all planetary Dashas.",
    category_id: "cat-navgraha",
    category: MAIN_BRACELET_CATEGORIES[2],
    price: 2499,
    sale_price: 1899,
    sale_start: null,
    sale_end: null,
    sku: "BRAC-NAV-9PL",
    stock_quantity: 50,
    track_inventory: true,
    allow_backorders: true,
    status: "active",
    meta_title: "Sacred Navgraha 9 Planet Bracelet - Yoginee",
    meta_description: "9 Planet planetary alignment bracelet for total protection & luck.",
    og_image_url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
    tags: ["Best Seller", "Navgraha", "Planetary", "Vedic", "9 Planets"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    avg_rating: 5.0,
    review_count: 240,
    images: [
      { id: "img-n1", product_id: "brac-navgraha-1", image_url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80", sort_order: 1, alt_text: "Navgraha Bracelet" },
    ],
  },
  {
    id: "brac-evileye-1",
    title: "Triple Protection Evil Eye & Black Obsidian Bracelet",
    slug: "triple-protection-evil-eye-black-obsidian-bracelet",
    description: "Powerful combination of Turkish Evil Eye bead, Black Tourmaline & Hematite. Creates an impenetrable auric shield against Nazar, negative jealousy, and psychic vampires.",
    category_id: "cat-protection",
    category: MAIN_BRACELET_CATEGORIES[3],
    price: 1599,
    sale_price: 1199,
    sale_start: null,
    sale_end: null,
    sku: "BRAC-EVI-OBS",
    stock_quantity: 60,
    track_inventory: true,
    allow_backorders: true,
    status: "active",
    meta_title: "Evil Eye Black Tourmaline Protection Bracelet - Yoginee",
    meta_description: "Nazar protection evil eye black obsidian bracelet.",
    og_image_url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80",
    tags: ["Protection", "Evil Eye", "Nazar", "Black Obsidian", "Best Seller"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    avg_rating: 4.9,
    review_count: 195,
    images: [
      { id: "img-e1", product_id: "brac-evileye-1", image_url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80", sort_order: 1, alt_text: "Evil Eye Bracelet" },
    ],
  },
  {
    id: "brac-7chakra-1",
    title: "7 Chakra Healing & Aura Alignment Bracelet",
    slug: "7-chakra-healing-aura-alignment-bracelet",
    description: "Features 7 natural healing crystals (Amethyst, Lapis Lazuli, Turquoise, Green Aventurine, Tiger's Eye, Carnelian & Red Jasper). Balances Root to Crown Chakras for deep vitality.",
    category_id: "cat-chakras",
    category: MAIN_BRACELET_CATEGORIES[5],
    price: 1799,
    sale_price: 1299,
    sale_start: null,
    sale_end: null,
    sku: "BRAC-7CH-ALA",
    stock_quantity: 40,
    track_inventory: true,
    allow_backorders: true,
    status: "active",
    meta_title: "7 Chakra Healing Energy Bracelet - Yoginee",
    meta_description: "Natural 7 Chakra stone bracelet for emotional and physical balance.",
    og_image_url: "https://images.unsplash.com/photo-1567225557594-88d73e55f2cb?w=800&q=80",
    tags: ["Chakra", "7 Chakra", "Healing", "Meditation", "Best Seller"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    avg_rating: 4.8,
    review_count: 156,
    images: [
      { id: "img-ch1", product_id: "brac-7chakra-1", image_url: "https://images.unsplash.com/photo-1567225557594-88d73e55f2cb?w=800&q=80", sort_order: 1, alt_text: "7 Chakra Bracelet" },
    ],
  },
  {
    id: "brac-rosequartz-1",
    title: "Natural Madagascar Rose Quartz Love & Harmony Bracelet",
    slug: "natural-madagascar-rose-quartz-love-harmony-bracelet",
    description: "Top tier Madagascar Rose Quartz crystal. Governed by Venus (Shukra). Opens the Heart Chakra, attracts soulmate love, heals emotional wounds, and fosters deep self-compassion.",
    category_id: "cat-love",
    category: MAIN_BRACELET_CATEGORIES[7],
    price: 1699,
    sale_price: 1199,
    sale_start: null,
    sale_end: null,
    sku: "BRAC-ROS-MAD",
    stock_quantity: 35,
    track_inventory: true,
    allow_backorders: true,
    status: "active",
    meta_title: "Rose Quartz Love & Relationship Bracelet - Yoginee",
    meta_description: "Genuine Rose Quartz crystal for love and emotional healing.",
    og_image_url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80",
    tags: ["Love", "Rose Quartz", "Venus", "Heart Chakra", "Harmony"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    avg_rating: 4.9,
    review_count: 98,
    images: [
      { id: "img-rq1", product_id: "brac-rosequartz-1", image_url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80", sort_order: 1, alt_text: "Rose Quartz Bracelet" },
    ],
  },
  {
    id: "brac-rudraksha-5m",
    title: "5 Mukhi Nepal Rudraksha & Silver Silver Capped Bracelet",
    slug: "5-mukhi-nepal-rudraksha-silver-capped-bracelet",
    description: "Authentic 5 Mukhi Nepal Rudraksha beads strung with 925 Sterling Silver capping. Blessed with Shiva energy for inner calmness, blood pressure regulation, and spiritual focus.",
    category_id: "cat-rudraksha",
    category: MAIN_BRACELET_CATEGORIES[6],
    price: 2999,
    sale_price: 2299,
    sale_start: null,
    sale_end: null,
    sku: "BRAC-RUD-5SIL",
    stock_quantity: 25,
    track_inventory: true,
    allow_backorders: true,
    status: "active",
    meta_title: "5 Mukhi Nepal Rudraksha Silver Bracelet - Yoginee",
    meta_description: "Pure Nepal Rudraksha 925 Sterling Silver bracelet.",
    og_image_url: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=80",
    tags: ["Rudraksha", "Shiva", "Silver", "Vedic", "Protection"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    avg_rating: 4.9,
    review_count: 130,
    images: [
      { id: "img-r5", product_id: "brac-rudraksha-5m", image_url: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=80", sort_order: 1, alt_text: "Rudraksha Silver Bracelet" },
    ],
  },
  {
    id: "brac-zodiac-sag",
    title: "Sagittarius (Dhanu Rashi) Lucky Birthstone Bracelet",
    slug: "sagittarius-dhanu-rashi-lucky-birthstone-bracelet",
    description: "Specially formulated for Sagittarius natives. Combines natural Yellow Sapphire (Pukhraj), Amethyst & Tiger's Eye to amplify Jupiter's wisdom, career expansion, and good fortune.",
    category_id: "cat-zodiac",
    category: MAIN_BRACELET_CATEGORIES[1],
    price: 2199,
    sale_price: 1699,
    sale_start: null,
    sale_end: null,
    sku: "BRAC-ZOD-SAG",
    stock_quantity: 20,
    track_inventory: true,
    allow_backorders: true,
    status: "active",
    meta_title: "Sagittarius Zodiac Birthstone Bracelet - Yoginee",
    meta_description: "Sagittarius Dhanu Rashi lucky gemstone bracelet.",
    og_image_url: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&q=80",
    tags: ["Zodiac", "Sagittarius", "Dhanu", "Jupiter", "Birthstone"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    avg_rating: 5.0,
    review_count: 67,
    images: [
      { id: "img-zs", product_id: "brac-zodiac-sag", image_url: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&q=80", sort_order: 1, alt_text: "Sagittarius Zodiac Bracelet" },
    ],
  },
  {
    id: "brac-tigerseye-1",
    title: "Golden Tiger's Eye Courage & Confidence Bracelet",
    slug: "golden-tigers-eye-courage-confidence-bracelet",
    description: "Natural chatoyant Golden Tiger's Eye. Governed by Sun & Mars. Instills fierce courage, removes fear of failure, boosts willpower, and protects during travel.",
    category_id: "cat-intention",
    category: MAIN_BRACELET_CATEGORIES[8],
    price: 1599,
    sale_price: 1099,
    sale_start: null,
    sale_end: null,
    sku: "BRAC-TIG-8MM",
    stock_quantity: 40,
    track_inventory: true,
    allow_backorders: true,
    status: "active",
    meta_title: "Tiger's Eye Confidence Bracelet - Yoginee",
    meta_description: "Natural Tiger's Eye gemstone bracelet for courage & focus.",
    og_image_url: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80",
    tags: ["Tiger's Eye", "Confidence", "Focus", "Intention"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    avg_rating: 4.8,
    review_count: 82,
    images: [
      { id: "img-te1", product_id: "brac-tigerseye-1", image_url: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80", sort_order: 1, alt_text: "Tiger's Eye Bracelet" },
    ],
  },
  {
    id: "brac-premium-navratna",
    title: "Luxury 925 Sterling Silver Navratna Gemstone Bracelet",
    slug: "luxury-925-sterling-silver-navratna-gemstone-bracelet",
    description: "Handcrafted 925 Sterling Silver setting with 9 authentic precious gemstones. Designed for royalty, royal planetary harmony, and lifelong prosperity.",
    category_id: "cat-premium",
    category: MAIN_BRACELET_CATEGORIES[9],
    price: 8999,
    sale_price: 6999,
    sale_start: null,
    sale_end: null,
    sku: "BRAC-PREM-NAV",
    stock_quantity: 10,
    track_inventory: true,
    allow_backorders: false,
    status: "active",
    meta_title: "Luxury 925 Sterling Silver Navratna Bracelet - Yoginee",
    meta_description: "Designer Navratna 925 sterling silver gemstone bracelet.",
    og_image_url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
    tags: ["Premium", "Silver", "Navratna", "Luxury", "Custom"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    avg_rating: 5.0,
    review_count: 42,
    images: [
      { id: "img-pn1", product_id: "brac-premium-navratna", image_url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80", sort_order: 1, alt_text: "Luxury Navratna Silver Bracelet" },
    ],
  },
];

export const RASHI_LIST = [
  { name: "Aries (Mesh)", icon: "♈", ruler: "Mars (Mangal)", element: "Fire", gemstone: "Red Coral & Tiger's Eye Bracelet", desc: "Mars energy amplifies your confidence. Today favors courageous initiatives." },
  { name: "Taurus (Vrishabha)", icon: "♉", ruler: "Venus (Shukra)", element: "Earth", gemstone: "Rose Quartz & Opal Bracelet", desc: "Venus brings financial harmony and artistic inspiration. Trust your intuition." },
  { name: "Gemini (Mithun)", icon: "♊", ruler: "Mercury (Budh)", element: "Air", gemstone: "Emerald & Green Aventurine", desc: "Mercury boosts strategic communication and business networking success." },
  { name: "Cancer (Kark)", icon: "♋", ruler: "Moon (Chandra)", element: "Water", gemstone: "Moonstone & Pearl Bracelet", desc: "Moon enhances emotional depth and domestic peace. Practice mindful meditation." },
  { name: "Leo (Simha)", icon: "♌", ruler: "Sun (Surya)", element: "Fire", gemstone: "Ruby & Citrine Abundance Bracelet", desc: "Surya bestows leadership authority and vitality. A vital day for decision making." },
  { name: "Virgo (Kanya)", icon: "♍", ruler: "Mercury (Budh)", element: "Earth", gemstone: "Green Aventurine & Pyrite Bracelet", desc: "Precision and analytical clarity are at their peak. Focus on structured goals." },
  { name: "Libra (Tula)", icon: "♎", ruler: "Venus (Shukra)", element: "Air", gemstone: "Rose Quartz & White Sapphire", desc: "Harmonious planetary alignment brings balance to partnerships and creative endeavors." },
  { name: "Scorpio (Vrishchik)", icon: "♏", ruler: "Mars (Mangal)", element: "Water", gemstone: "Red Coral & Black Tourmaline Shield", desc: "Deep transformative energy opens new spiritual insights and financial breakthroughs." },
  { name: "Sagittarius (Dhanu)", icon: "♐", ruler: "Jupiter (Guru)", element: "Fire", gemstone: "Yellow Sapphire & Pyrite Bracelet", desc: "Jupiter's blessing radiates wisdom, spiritual expansion, and lucky opportunities." },
  { name: "Capricorn (Makar)", icon: "♑", ruler: "Saturn (Shani)", element: "Earth", gemstone: "Blue Sapphire & Black Obsidian Shield", desc: "Saturn rewards diligent patience and long-term perseverance with firm success." },
  { name: "Aquarius (Kumbh)", icon: "♒", ruler: "Saturn (Shani)", element: "Air", gemstone: "Blue Sapphire & Amethyst Bracelet", desc: "Innovative thoughts and humanitarian projects gain positive momentum today." },
  { name: "Pisces (Meen)", icon: "♓", ruler: "Jupiter (Guru)", element: "Water", gemstone: "Amethyst & Citrine Crystal Bracelet", desc: "Intuitive perception is heightened. Ideal for spiritual Sadhana and crystal healing." },
];
